package com.yangfeilong.live.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.yangfeilong.live.common.model.base.BaseTempComment;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TempComment extends BaseTempComment<TempComment> {
	public static final TempComment dao = new TempComment().dao();
	public boolean deleteByNickName(String param){
		try{
			param="'"+param+"'";
			List<TempComment> list=dao.find("select * from l_temp_comment where nick_name="+param);
			for(TempComment tempComment:list){
				tempComment.delete();
			}
		}catch (Exception e){
			e.printStackTrace();
			return false;
		}
		return true;
	}
}
