package com.yangfeilong.live.common.model;

import com.yangfeilong.live.common.model.base.BaseUpdator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Updator extends BaseUpdator<Updator> {
	public static final Updator dao = new Updator().dao();
}
