package com.yangfeilong.live.common.model;

import com.yangfeilong.live.common.model.base.BaseVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Video extends BaseVideo<Video> {
	public static final Video dao = new Video().dao();
}
