package com.yangfeilong.live.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTempComment<M extends BaseTempComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setMode(java.lang.Integer mode) {
		set("mode", mode);
		return (M)this;
	}

	public java.lang.Integer getMode() {
		return getInt("mode");
	}

	public M setCommentTime(java.util.Date commentTime) {
		set("comment_time", commentTime);
		return (M)this;
	}

	public java.util.Date getCommentTime() {
		return get("comment_time");
	}

}
