package com.yangfeilong.live.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}

	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}

	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}

	public java.lang.String getRealName() {
		return getStr("real_name");
	}

	public M setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
		return (M)this;
	}

	public java.lang.String getPhoneNumber() {
		return getStr("phone_number");
	}

	public M setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
		return (M)this;
	}

	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public M setVideoAmount(java.lang.Integer videoAmount) {
		set("video_amount", videoAmount);
		return (M)this;
	}

	public java.lang.Integer getVideoAmount() {
		return getInt("video_amount");
	}

	public M setRegTime(java.util.Date regTime) {
		set("reg_time", regTime);
		return (M)this;
	}

	public java.util.Date getRegTime() {
		return get("reg_time");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setWatchNum(java.lang.Integer watchNum) {
		set("watch_num", watchNum);
		return (M)this;
	}

	public java.lang.Integer getWatchNum() {
		return getInt("watch_num");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return getInt("level");
	}

}
