package com.yangfeilong.live.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUpdator<M extends BaseUpdator<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setVersion(java.lang.String version) {
		set("version", version);
		return (M)this;
	}

	public java.lang.String getVersion() {
		return getStr("version");
	}

	public M setLog(java.lang.String log) {
		set("log", log);
		return (M)this;
	}

	public java.lang.String getLog() {
		return getStr("log");
	}

	public M setConstraintion(java.lang.Boolean constraintion) {
		set("constraintion", constraintion);
		return (M)this;
	}

	public java.lang.Boolean getConstraintion() {
		return get("constraintion");
	}

	public M setSize(java.lang.String size) {
		set("size", size);
		return (M)this;
	}

	public java.lang.String getSize() {
		return getStr("size");
	}

}
